#请求host地址
Host: https://sitqone-wh.quarkfinance.com
#用例文件路径
Casefile: D:\GitPro\Python\PythonApiTest\TestCase\TestData\Qone.yaml
#Casefile: /Users/Sky/developer/PycharmProjects/PythonApiTest/TestCase/TestData/Qone.yaml
#临时文件路径
#tempfile: /Users/Sky/developer/PycharmProjects/PythonApiTest/output/tempyaml.yaml
tempfile: D:\GitPro\Python\PythonApiTest\output\tempyaml.yaml
#请求header内容
#Header:
#  test1: '123456'
#  test2: '123456'
#秘钥
Secrete: 'B4B83DC748B8E511A2846C0B840997C3'
#用户自定义参数
UserParm:
  $deviceversion$: '112'
  $account$: '15502168672'
  $password$: 'zaq123'
  $veron$: '1.0'
